### ISSUE TITLE
failed to parse some pkcs7 cert

### ISSUE THREAD

**Issue by virusdefender** [sassoftware/relic#11]
[explorer.exe.zip](https://github.com/sassoftware/relic/files/6371402/explorer.exe.zip)

the error message is 

```
 asn1: structure error: tags don't match (16 vs {class:2 tag:1 length:719 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} certificate @4
```

**Comment by mtharp** [comment]
Thanks for the report. It looks like Microsoft is adding an extra cert to its timestamps that has a badly-formatted version field, perhaps for backwards compatibility.

This patch will ignore the parse error as long as the other certs are sufficient to build a trust chain.
