### ISSUE TITLE
comdoc writeat: negative offset

### ISSUE THREAD

**Issue by gabriel-vasile** [sassoftware/relic#29]
I'm not sure if this a bug in library code or a problem with the file that I used for test.

```go
package main

import (
	"fmt"

	"github.com/sassoftware/relic/v7/lib/comdoc"
)

func main() {
	doc, err := comdoc.WritePath("xls.xls")
	if err != nil {
		fmt.Println(err)
	}

	if err := doc.AddFile("filename", []byte{1, 2, 3}); err != nil {
		fmt.Println(err)
	}
}
```

expected: `doc.AddFile` returns nil
what happened: `doc.AddFile` returns `writeat xls.xls: negative offset`

[xls.xls](https://github.com/sassoftware/relic/files/11799397/xls.xls)

**Comment by mtharp** [comment]
relic's comdoc package really only supports MSI files, and even then just the bare minimum to store and validate signatures. I'm happy to accept pull requests if they don't interfere with the main functionality but unfortunately I don't have time to chase down issues myself, sorry!
