### ISSUE TITLE
fail to sign msi

### ISSUE THREAD

**Issue by RangoW** [sassoftware/relic#6]
Hi, i got to sign a .msi，but report error “
`PS C:\Users\rango> relic.exe sign -k my_file_key -c C:\Users\rango\Documents\relic_config\relic.yml -f ..\..\testdata\setup.msi -d 9        ERROR: archive/tar: missed writing 3194 bytes`
”  
what dose this error mean.....😭

**Comment by antoinedeschenes** [comment]
Reviving old issues, this seems to be fixed in 7.3.0
