### ISSUE TITLE
macOS signging

### ISSUE THREAD

**Issue by directionless** [sassoftware/relic#7]
Hi! Have you looked at adding in macOS code signing support?

Unfortunately, I don't know if there are cross platform ways to do it. In my own tools, I'm using Exec to call out

**Comment by antoinedeschenes** [comment]
> Added signing and verification of Apple Mach-O binaries, DMG disk images and PKG flat installer files

**Comment by mtharp** [comment]
It's not fully fleshed out but there's enough to get started with: https://github.com/sassoftware/relic/blob/master/doc/macos.md

Feedback is welcome.
