### ISSUE TITLE
Arch Linux pkg.tar.zst/pkg.tar.xz support 

### ISSUE THREAD

**Issue by shibumi** [sassoftware/relic#8]
Hi,
Is there any guide for adding a new pkg format? I would be willing to donate a patch for adding support for Arch Linux based distributions, but I don't know where to start :)

**Comment by mtharp** [comment]
It looks like Arch uses PGP detached signatures adjacent to the file, so you can use the sign-pgp or remote sign-pgp subcommand like this:
```
relic sign-pgp -u keyname -b mypackage.tar.zst -o mypackage.tar.zst.sig
```
The sign-pgp command takes options similar to gpg, so you might be able to configure the arch packaging tools to call relic instead without a wrapper.

**Comment by shibumi** [comment]
Hey @mtharp This is sufficient I guess, I didn't know it's that easy. I close this issue, because it's answered.
